// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chifftwhhzklnauykhcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoaWZmdHdoaHprbG5hdXlraGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDMwODYsImV4cCI6MjA2NDE3OTA4Nn0.VE38ZjxAf9H4fGR2Ot1WIz13zbvEg4C0aaL74AtT5bA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);